server/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

locale_urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('textrank.urls')),
]

urlpatterns = i18n_patterns(
    path('', include(locale_urlpatterns)),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

textrank/urls.py
#
# Copyright (c) 2019, Grigoriy Kramarenko
# All rights reserved.
# This file is distributed under the BSD 3-Clause License.
#
from django.urls import path
from textrank.views import (
    index, groups, keywords, rank, weightform, samples, topics
)

app_name = 'textrank'


urlpatterns = [
    path('', index, name='index'),
    path('groups/', groups, name='groups'),
    path('groups/<int:id>/', groups, name='group'),
    path('keywords/', keywords, name='keywords'),
    path('keywords/<int:id>/', keywords, name='keyword'),
    path('rank/', rank, name='rank'),
    path('rank/<str:format>/', rank, name='rank'),
    path('weightform/', weightform, name='add_weight'),
    path('weightform/<int:id>/', weightform, name='change_weight'),
    path('samples/', samples, name='samples'),
    path('samples/<int:id>/', samples, name='sample'),
    path('topics/', topics, name='topics'),
    path('topics/<int:id>/', topics, name='topic'),
]

textrank/models.py
#
# Copyright (c) 2019, Grigoriy Kramarenko
# All rights reserved.
# This file is distributed under the BSD 3-Clause License.
#
from collections import OrderedDict
from hashlib import md5
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.timezone import now
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _

from textrank.validators import keyword_validator


class Topic(models.Model):
    """Раздел для группировки ранжирования."""
    created = models.DateTimeField(_('создан'), auto_now_add=True)
    updated = models.DateTimeField(_('обновлён'), auto_now=True)
    name = models.CharField(
        _('название'), max_length=150, unique=True,
        help_text=_('Обязательно. 150 символов и менее.'),
        error_messages={
            'unique': _('Такое название уже существует.'),
        },
    )
    description = models.TextField(
        _('описание'), blank=True, db_index=True,
    )
    code = models.CharField(
        _('код раздела'), max_length=32, default=get_random_string, unique=True,
        help_text=_('Обязательно. 32 символа и менее, уникальное значение.'),
        error_messages={
            'unique': _('Такой код уже существует.'),
        },
    )
    is_active = models.BooleanField(
        _('активный'), default=True, db_index=True, help_text=_(
            'Отключите, если раздел не используется для анализа.'
        )
    )
    # Пользователь, который последним изменил объект.
    last_editor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        editable=False,
        verbose_name=_('последний редактор'),
        on_delete=models.PROTECT,
    )

    class Meta:
        verbose_name = _('раздел ранжирования')
        verbose_name_plural = _('разделы ранжирования')
        ordering = ('name',)

    def __str__(self):
        return self.name

    def delete(self, **kwargs):
        # Удалять объекты в Django запрещено. Только из базы данных.
        self.is_active = False
        self.save(**kwargs)

    def get_description(self):
        return self.description.replace('\r\n', ' ').replace('\n', ' ')


class Group(models.Model):
    """Модель группы ключевых слов."""
    created = models.DateTimeField(_('создана'), auto_now_add=True)
    updated = models.DateTimeField(_('обновлена'), auto_now=True)

    name = models.CharField(
        _('название'), max_length=150,
        help_text=_('Обязательно. 150 символов и менее.'),
        error_messages={
            'unique': _('Такое название уже существует.'),
        },
    )
    description = models.TextField(
        _('описание'), blank=True, db_index=True,
    )
    code = models.CharField(
        _('код группы'), max_length=32, default=get_random_string,
        help_text=_('Обязательно. 32 символа и менее, уникальное значение.'),
        error_messages={
            'unique': _('Такой код уже существует.'),
        },
    )
    is_active = models.BooleanField(
        _('активная'), default=True, db_index=True, help_text=_(
            'Отключите, если группа не используется для анализа.'
        )
    )
    topic = models.ForeignKey(
        Topic,
        null=True, blank=True,
        verbose_name=_('раздел'),
        on_delete=models.PROTECT,
    )
    # Пользователь, который последним изменил объект.
    last_editor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        editable=False,
        verbose_name=_('последний редактор'),
        on_delete=models.PROTECT,
    )

    class Meta:
        verbose_name = _('группа ключевых слов')
        verbose_name_plural = _('группы ключевых слов')
        ordering = ('name',)
        constraints = [
            models.UniqueConstraint(
                fields=['name'], name='group_name_default_unique',
                condition=models.Q(topic__isnull=True),
            ),
            models.UniqueConstraint(
                fields=['name', 'topic'], name='group_name_topic_unique',
                condition=models.Q(topic__isnull=False),
            ),
            models.UniqueConstraint(
                fields=['code'], name='group_code_default_unique',
                condition=models.Q(topic__isnull=True),
            ),
            models.UniqueConstraint(
                fields=['code', 'topic'], name='group_code_topic_unique',
                condition=models.Q(topic__isnull=False),
            ),
        ]

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        super().save(**kwargs)
        # Обновляем все веса, чтобы анализатор перезагрузил данные.
        Weight.objects.filter(group=self).update(updated=now())

    def delete(self, **kwargs):
        # Удалять объекты в Django запрещено. Только из базы данных.
        self.is_active = False
        self.save(**kwargs)

    def get_all_keywords(self):
        return self.keyword_set.all()

    def get_active_keywords(self):
        return self.get_all_keywords().filter(is_active=True)

    def get_inactive_keywords(self):
        return self.get_all_keywords().filter(is_active=False)

    def get_all_weights(self):
        qs = self.weights.select_related('group', 'keyword')
        qs = qs.order_by('keyword__word')
        return qs

    def get_description(self):
        return self.description.replace('\r\n', ' ').replace('\n', ' ')


class Keyword(models.Model):
    """Модель ключевого слова или словосочетания."""

    created = models.DateTimeField(_('создано'), auto_now_add=True)
    updated = models.DateTimeField(_('обновлено'), auto_now=True)
    word = models.CharField(
        _('слово'), max_length=100,
        help_text=_(
            'Обязательно. 100 символов и менее. '
            'Значение может содержать только буквы в нижнем регистре, '
            'цифры, символы дефиса, подчёркивания или знак +, а также '
            'начинаться и заканчиваться словом. Варианты: '
            'Ключевое слово (word1), цепочка слов (word1_word2_word3) '
            'или покрытие словами (word1+word2+word3).'
        ),
        validators=[keyword_validator],
        error_messages={
            'unique': _('Такое слово (сочетание) уже существует.'),
        },
    )
    is_active = models.BooleanField(
        _('активное'), default=True, db_index=True, help_text=_(
            'Отключите, если слово не используется для анализа.'
        )
    )
    topic = models.ForeignKey(
        Topic,
        null=True, blank=True,
        verbose_name=_('раздел'),
        on_delete=models.PROTECT,
    )
    # Пользователь, который последним изменил объект.
    last_editor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        editable=False,
        verbose_name=_('последний редактор'),
        on_delete=models.PROTECT,
    )
    groups = models.ManyToManyField(
        Group, through='Weight',
        editable=False,
        verbose_name=_('группы')
    )

    class Meta:
        verbose_name = _('ключевое слово')
        verbose_name_plural = _('ключевые слова')
        ordering = ('word',)
        constraints = [
            models.UniqueConstraint(
                fields=['word'], name='keyword_default_unique',
                condition=models.Q(topic__isnull=True),
            ),
            models.UniqueConstraint(
                fields=['word', 'topic'], name='keyword_topic_unique',
                condition=models.Q(topic__isnull=False),
            ),
        ]

    def __str__(self):
        return self.word

    @staticmethod
    def validate_word(word, raise_error=False):
        try:
            keyword_validator(word)
        except ValidationError as e:
            if raise_error:
                raise e
            return False
        return True

    @property
    def is_chain(self):
        return '_' in self.word

    @property
    def is_cover(self):
        return '+' in self.word

    @property
    def chainwords(self):
        w = self.word
        if '_' in w:
            words = [x for x in w.split('_') if x]
            if len(words) >= 2:
                return words
        return []

    @property
    def coverwords(self):
        w = self.word
        if '+' in w:
            words = [x for x in w.split('+') if x]
            if len(words) >= 2:
                return words
        return []

    def get_all_groups(self):
        return self.groups.all()

    def get_active_groups(self):
        return self.get_all_groups().filter(is_active=True)

    def get_inactive_groups(self):
        return self.get_all_groups().filter(is_active=False)

    def get_weight_groups(self):
        groups = OrderedDict([(g.id, [g, None]) for g in Group.objects.all()])
        for w in self.weights.select_related('group', 'keyword'):
            groups[w.group_id][1] = w
        return groups

    def save(self, **kwargs):
        self.validate_word(self.word, True)
        super().save(**kwargs)
        # Обновляем все веса, чтобы анализатор перезагрузил данные.
        Weight.objects.filter(keyword=self).update(updated=now())

    def delete(self, **kwargs):
        # Удалять объекты в Django запрещено. Только из базы данных.
        self.is_active = False
        self.save(**kwargs)


class Weight(models.Model):
    """Модель веса ключевого слова для группы."""
    created = models.DateTimeField(_('создан'), auto_now_add=True)
    updated = models.DateTimeField(_('обновлён'), auto_now=True, db_index=True)
    group = models.ForeignKey(
        Group,
        verbose_name=_('группа'),
        on_delete=models.PROTECT,
        related_name='weights',
    )
    keyword = models.ForeignKey(
        Keyword,
        verbose_name=_('ключевое слово'),
        on_delete=models.PROTECT,
        related_name='weights',
    )
    value = models.PositiveSmallIntegerField(_('значение веса'), default=1)

textrank/views/base.py
#
# Copyright (c) 2019, Grigoriy Kramarenko
# All rights reserved.
# This file is distributed under the BSD 3-Clause License.
#
from json import loads

from django.http import QueryDict, HttpResponseForbidden, JsonResponse
from django.shortcuts import get_object_or_404, resolve_url
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt

from djangokit.views import controller

from textrank import __version__
from textrank.conf import LOGIN_URL, LOGOUT_URL, DEMO_MODE, JSON_DUMPS_PARAMS
from textrank.decorators import user_access_required, api_access_required


def get_default_context():
    ctx = {
        'VERSION': __version__,
        'LOGIN_URL': resolve_url(LOGIN_URL),
        'LOGOUT_URL': resolve_url(LOGOUT_URL),
        'DEMO_MODE': DEMO_MODE,
    }
    return ctx


def parse_params(request):
    if request.content_type == 'application/json':
        return loads(request.body.decode('utf-8'))
    method = request.method
    if method == 'GET':
        return request.GET
    elif method == 'POST':
        return request.POST
    return QueryDict(request.body)


@method_decorator(user_access_required, name='dispatch')
class UserAccessMixin:
    """Mixing for user access."""

    def dispatch(self, request, *args, **kwargs):
        if DEMO_MODE and request.method != 'GET':
            # В демо-режиме не позволяем анонимам изменять данные.
            if not request.user.is_authenticated:
                return HttpResponseForbidden(_(
                    'Авторизируйтесь, чтобы иметь возможность редактировать '
                    'данные.'
                ))
        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)


@method_decorator(csrf_exempt, name='dispatch')
@method_decorator(api_access_required, name='dispatch')
class ApiAccessMixin:
    """Mixing for API access."""
    def dispatch(self, *args, **kwargs):
        return super(ApiAccessMixin, self).dispatch(*args, **kwargs)


class BaseModelView(controller.ControlModelView):

    def get_default_context(self, *args, **kwargs):
        return get_default_context()

    def render_to_json_response(self, ctx):
        form = ctx['form']
        if form.is_bound and form._errors:
            data = {'errors': form.errors.get_json_data()}
            return JsonResponse(data, json_dumps_params=JSON_DUMPS_PARAMS,
                                status=400)

        instance = ctx['instance']
        if instance:
            data = self.ctrl.serialize(instance)
        else:
            data = {
                'page': self.ctrl.serialize_page(ctx['page'], None),
                'orders': ctx['orders'],
                'filters': ctx['filters'],
            }
        return JsonResponse(data, json_dumps_params=JSON_DUMPS_PARAMS)

    def render_to_response(self, ctx):
        if self.request.GET.get('format') == 'json':
            return self.render_to_json_response(ctx)
        return super().render_to_response(ctx)

    def delete(self, request, id=None):
        if id:
            instance = get_object_or_404(self.model, id=id)
            instance.delete()
        else:
            self.model.objects.all().delete()
        return JsonResponse({'success': True, 'id': id})

textrank/templates/textrank/_is_active_button.html
{% load i18n navigation %}
{% if filters.is_active is True %}
    <a href="{{ path }}{% delparams request 'is_active' %}" class="btn btn-sm btn-outline-secondary active">
        <span class="fa fa-eye"></span>
        <span class="ml-1">{% trans 'показать неактивные' %}</span>
    </a>
{% else %}
    <a href="{{ path }}{% addparams request is_active='true' %}" class="btn btn-sm btn-outline-secondary">
        <span class="fa fa-eye-slash"></span>
        <span class="ml-1">{% trans 'скрыть неактивные' %}</span>
    </a>
{% endif %}

textrank/templates/textrank/_search_form.html
{% load i18n %}
<form class="form-inline">
    <input class="form-control form-control-sm" type="search" name="q" value="{{ request.GET.q }}" placeholder="{% trans 'поиск' %}" aria-label="{% trans 'поиск' %}">
{% for name, value in request.GET.items %}
{% if name != 'q' %}
    <input type="hidden" name="{{ name }}" value="{{ value|iriencode }}">
{% endif %}
{% endfor %}
    <button class="btn btn-sm btn-outline-success ml-1" type="submit">
        <span class="fa fa-search"></span>
    </button>
</form>

textrank/templates/textrank/_table_pagination.html
{% load i18n navigation  %}
<nav aria-label="{% trans 'Постраничная навигация' %}">
    <ul class="pagination pagination-sm justify-content-end">
        <li class="mr-1">
            <div class="dropdown">
            {% with 'dropdown'|guid as id %}
            {% with page.paginator.per_page|stringformat:'d' as per_page %}
                <button class="btn btn-secondary btn-sm" type="button" id="{{ id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span>{{ per_page }} {% trans 'на страницу' %}</span>
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="{{ id }}">
                {% for v in '5,10,15,25,50,100,250,500'|split %}
                    <a class="dropdown-item{% if per_page == v %} active{% endif %}" href="{% addparams request l=v %}">{{ v }}</a>
                {% endfor %}
                </div>
            {% endwith %}
            {% endwith %}
            </div>
        </li>
{% for p in page|make_page_range %}
    {% if p == page.number %}
        <li class="page-item active"><a class="page-link text-light bg-dark" href="{% addparams request p=p %}">{{ p }}</a></li>
    {% elif p == '.' %}
        <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
    {% else %}
        <li class="page-item"><a class="page-link text-muted" href="{% addparams request p=p %}">{{ p }}</a></li>
    {% endif %}
{% endfor %}
    </ul>
</nav>

textrank/templates/textrank/groups.html
{% extends './base.html'%}
{% load i18n bootstrap4 html navigation %}

{% block body_class %}groups{% endblock %}

{% block content %}{% newlineless %}{% spaceless %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'textrank:index' %}">TextRank</a></li>
        <li class="breadcrumb-item active" aria-current="page">{% trans 'Группы' %}</li>
    </ol>
</nav>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
{% if instance %}
    <h1 class="h2">{% trans 'Группа' %} #{{ instance.id }}</h1>
{% else %}
    <h1 class="h2">{% trans 'Группы' %}</h1>
{% endif %}
    <div class="btn-toolbar mb-2 mb-md-0">
    {% if instance %}
        <div class="btn-group">
            <a href="{% url 'textrank:groups' %}" class="btn btn-sm btn-outline-secondary">
                <span class="ml-1">{% trans 'Список групп' %}</span>
            </a>
        </div>
    {% else %}
        {% url 'textrank:groups' as path %}
        <div class="btn-group mr-2">{% include './_search_form.html' %}</div>
        <div class="btn-group">
            <a href="#form" class="btn btn-sm btn-outline-secondary">
                <span class="fa fa-plus"></span>
                <span class="ml-1">{% trans 'добавить' %}</span>
            </a>
            {% include './_is_active_button.html' with path=path %}
        </div>
        <div class="dropdown mr-0">
            <button type="button" id="dropdownMenuOrdering" data-toggle="dropdown" \
                aria-haspopup="true" aria-expanded="false" \
                class="btn btn-sm btn-outline-secondary ml-2 dropdown-toggle \
                {% if orders %}active{% endif %}">
                <span class="fa fa-sort"></span>
                <span class="ml-1">{% trans 'сортировка' %}</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuOrdering">
                <a href="{{ path }}{% delparams request 'o' %}" \
                    class="dropdown-item {% if not orders %}active{% endif %}"> \
                    name \
                </a>
                <a href="{{ path }}{% addparams request o='-name' %}" \
                    class="dropdown-item {% if orders_string == '-name' %}active{% endif %}"> \
                    -name \
                </a>
                <a href="{{ path }}{% addparams request o='is_active,name' %}" \
                    class="dropdown-item {% if orders_string == 'is_active,name' %}active{% endif %}"> \
                    is_active,name \
                </a>
                <a href="{{ path }}{% addparams request o='-is_active,name' %}" \
                    class="dropdown-item {% if orders_string == '-is_active,name' %}active{% endif %}"> \
                    -is_active,name \
                </a>
                <a href="{{ path }}{% addparams request o='updated' %}" \
                    class="dropdown-item {% if orders_string == 'updated' %}active{% endif %}"> \
                    updated \
                </a>
                <a href="{{ path }}{% addparams request o='-updated' %}" \
                    class="dropdown-item {% if orders_string == '-updated' %}active{% endif %}"> \
                    -updated \
                </a>
                <a href="{{ path }}{% addparams request o='created' %}" \
                    class="dropdown-item {% if orders_string == 'created' %}active{% endif %}"> \
                    created \
                </a>
                <a href="{{ path }}{% addparams request o='-created' %}" \
                    class="dropdown-item {% if orders_string == '-created' %}active{% endif %}"> \
                    -created \
                </a>
                <a href="{{ path }}{% addparams request o='last_editor__username' %}" \
                    class="dropdown-item {% if orders_string == 'last_editor__username' %}active{% endif %}"> \
                    last_editor__username \
                </a>
                <a href="{{ path }}{% addparams request o='-last_editor__username' %}" \
                    class="dropdown-item {% if orders_string == '-last_editor__username' %}active{% endif %}"> \
                    -last_editor__username \
                </a>
                <a href="{{ path }}{% addparams request o='id' %}" \
                    class="dropdown-item {% if orders_string == 'id' %}active{% endif %}"> \
                    id \
                </a>
                <a href="{{ path }}{% addparams request o='-id' %}" \
                    class="dropdown-item {% if orders_string == '-id' %}active{% endif %}"> \
                    -id \
                </a>
            </div>
        </div>
    {% endif %}
    </div>
</div>

{% if not instance %}
<div class="table-responsive">
    <table class="table table-striped table-sm mb-3">
        <thead class="bg-dark text-white">
            <tr>
                <th>{% trans 'Название' %}</th>
                <th>{% trans 'Код' %}</th>
                <th>{% trans 'Раздел' %}</th>
                <th class="text-right">{% trans 'Слов' %}</th>
                <th>{% trans 'Активна' %}</th>
                <th>{% trans 'Создана' %}</th>
                <th>{% trans 'Обновлена' %}</th>
                <th>{% trans 'Редактор' %}</th>
                <th>ID</th>
            </tr>
        </thead>
        <tbody>
        {% url 'textrank:keywords' as keywords_url %}
        {% for group in page.object_list %}
            <tr>
                <td>
                    <a class="text-body" href="{% url 'textrank:group' id=group.id %}">{{ group.name }}</a>
                {% if group.description %}
                    <span class="fa fa-question-circle-o ml-1 text-muted" title="{{ group.get_description }}"></span>
                {% endif %}
                </td>
                <td><small class="text-monospace">{{ group.code }}</small></td>
                <td><small class="text-monospace">{{ group.topic|default:'---' }}</small></td>
                <td class="text-right"><a href="{{ keywords_url }}?groups={{ group.id }}" class="text-body">{{ group.keywords_count }}</a></td>
                <td>
                {% if group.is_active %}
                    <span class="fa fa-check"></span>
                {% endif %}
                </td>
                <td class="text-nowrap isoformat">{{ group.created.isoformat }}</td>
                <td class="text-nowrap isoformat">{{ group.updated.isoformat }}</td>
                <td>{{ group.last_editor|default:'---' }}</td>
                <td>{{ group.id }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="8">{% trans 'Не найдено ни одной записи.' %}</td>
            </tr>
        {% endfor %}
        </tbody>
    {% if page.object_list %}
        <tfoot>
            <tr>
                <td colspan="8" class="pr-0">{% include './_table_pagination.html' %}</td>
            </tr>
        </tfoot>
    {% endif %}
    </table>
</div>
<h2 class="h3">{% trans 'Добавить новую группу' %}</h2>
{% endif %}

{% if instance %}
<p>
    <span class="badge badge-pill badge-dark m-1">{% trans 'ID' %}: {{ instance.id }}</span>
    <span class="badge badge-pill badge-secondary m-1">{% trans 'создана' %}: <span class="isoformat">{{ instance.created.isoformat }}</span></span>
    <span class="badge badge-pill badge-warning m-1">{% trans 'обновлена' %}: <span class="isoformat">{{ instance.updated.isoformat }}</span> {{ instance.last_editor }}</span>
    <span class="badge badge-pill badge-info m-1">{% trans 'всего слов' %}: {{ instance.get_all_keywords.count }}</span>
    <span class="badge badge-pill badge-success m-1">{% trans 'активных слов' %}: {{ instance.get_active_keywords.count }}</span>
    <span class="badge badge-pill badge-danger m-1">{% trans 'неактивных слов' %}: {{ instance.get_inactive_keywords.count }}</span>
</p>
{% endif %}

<form id="form" class="form bg-light p-2 mb-4" role="form" method="post" enctype="multipart/form-data">
    <input type="hidden" name="next" value="{{ next|escape }}" />
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
    <div class="row">
        <div class="col-md-6">
            {{ form.name|form_group }}
            {{ form.code|form_group }}
            {{ form.topic|form_group }}
            {{ form.is_active|form_group }}
        </div>
        <div class="col-md-6">{{ form.description|form_group }}</div>
    </div>
    <button type="submit" class="btn btn-dark">
        <i class="fa fa-save" aria-hidden="true"></i> \
        {% trans 'Сохранить' %} \
    </button>
</form>

{% if instance %}
<h2 id="weights" class="h3">{% trans 'Таблица весов' %}</h2>
<div class="table-responsive">
    <table class="table table-bordered table-sm mb-3">
        <thead class="bg-dark text-white">
            <tr>
                <th>{% trans 'Слово или сочетание' %}</th>
                <th style="width: 1px;">{% trans 'Вес' %}</th>
                <th style="width: 1px;">{% trans 'Активен' %}</th>
                <th>{% trans 'Обновлён' %}</th>
                <th>{% trans 'Редактор' %}</th>
            </tr>
        </thead>
        <tbody>
        {% url 'textrank:add_weight' as add_weight_url %}
        {% for weight in instance.get_all_weights %}
            <tr>
                <td class="align-middle">
                    <a href="{% url 'textrank:keyword' id=weight.keyword_id %}" class="text-body">{{ weight.keyword }}</a>
                </td>
                <td class="align-middle">
                    <form class="form-inline" method="post" action="{% if weight %}{% url 'textrank:change_weight' id=weight.id %}{% else %}{{ add_weight_url }}{% endif %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}#weights">
                        <input type="hidden" name="group" value="{{ instance.id }}">
                        <input type="hidden" name="keyword" value="{{ weight.keyword.id }}">
                        <div class="input-group input-group-sm mb-0">
                            <input type="number" \
                                min="0" max="32767" required name="value"
                                class="form-control save-weight" \
                                data-saveid="{{ weight.keyword.id }}" \
                            {% if weight %}
                                data-initial="{{ weight.value }}" \
                                value="{{ weight.value }}" \
                            {% endif %}
                                aria-describedby="button-{{ weight.keyword.id }}">
                            <div class="input-group-append">
                                <button id="button-{{ weight.keyword.id }}" \
                                    class="btn btn-outline-secondary save-weight save-weight-{{ weight.keyword.id }}" \
                                    type="submit" disabled>
                                    <i class="fa fa-save"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </td>
            {% if weight %}
                <td class="text-center align-middle">
                    <span class="fa fa-{{ weight.is_active|yesno:'check,ban' }}"></span>
                </td>
                <td class="isoformat align-middle">{{ weight.updated.isoformat }}</td>
                <td class="align-middle">{{ weight.last_editor}}</td>
            {% else %}
                <td></td>
                <td></td>
                <td></td>
            {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<a href="{% url 'textrank:index' %}?groups={{ instance.name }}" class="btn btn-outline-secondary mb-5">
    <span>{% trans 'Добавить слова' %}</span>
</a>
{% endif %}

{% endspaceless %}{% endnewlineless %}{% endblock %}

{% block javascript_page %}{% newlineless_javascript %}
<script type="text/javascript">
function activateButton(e) {
    var el = $(this),
        access = (el.data('initial') || '') != el.val();
    $('button.save-weight-' + el.data('saveid'))
        .toggleClass('active', access)
        .prop('disabled', !access)
}

$(document).ready(function($) {
    var language = $('html').attr('lang') || 'ru';
    moment.updateLocale(language, {});
    // Перерисовываем ISO дату по локальному времени юзера.
    $('.isoformat').each(function(i, el) {
        var $el = $(el);
        $el.text(moment($el.text()).format('L LT'));
    });
{% if user.is_authenticated %}
    $('body')
        .on('keyup', '.save-weight', activateButton)
        .on('change', '.save-weight', activateButton)
    ;
{% endif %}
{% if DEMO_MODE and not user.is_authenticated %}
    $('#form').on('submit', function(e) {
        e.preventDefault();
        alert("{% trans 'Это демо-режим, авторизуйтесь, чтобы изменять данные.' %}")
    });
{% endif %}
})
</script>
{% endnewlineless_javascript %}{% endblock %}